name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ant
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Build with Buildozer
      run: |
        ls -la
        pwd
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mix-cd-scrobbler-debug.apk
        path: bin/*.apk
