name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Use pre-installed Android SDK
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "PATH=/usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Accept SDK licenses with pre-installed tools
      run: |
        yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Create simple buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = Mix CD Scrobbler
        package.name = mixcdscrobbler
        package.domain = org.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas,json
        version = 0.1
        requirements = python3,kivy,requests

        [buildozer]
        log_level = 2

        [app:android]
        bootstrap = sdl2
        android.accept_sdk_license = True
        android.archs = arm64-v8a
        android.permissions = INTERNET,ACCESS_NETWORK_STATE
        EOF

    - name: Build APK
      run: |
        buildozer android debug --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mix-cd-scrobbler-apk
        path: bin/*.apk
