name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'  # Changed back to Java 11 for better compatibility

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 29  # Use older API level for better compatibility
        build-tools: 29.0.3
        ndk-version: 21.4.7075529  # Use older NDK that works better with libffi

    - name: Install system dependencies for autotools
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython

    - name: Accept buildozer SDK licenses
      run: |
        export BUILDOZER_ANDROID_ACCEPT_SDK_LICENSE=1
        echo "BUILDOZER_ANDROID_ACCEPT_SDK_LICENSE=1" >> $GITHUB_ENV

    - name: Build APK with simpler configuration
      run: |
        # Create a minimal buildozer.spec for testing
        cat > buildozer.spec << EOF
        [app]
        title = Mix CD Scrobbler
        package.name = mixcdscrobbler
        package.domain = org.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas,json
        version = 0.1
        requirements = python3,kivy,requests

        [buildozer]
        log_level = 2

        [app:android]
        bootstrap = sdl2
        android.accept_sdk_license = True
        android.api = 29
        android.minapi = 21
        android.sdk = 29
        android.ndk = 21b
        android.archs = arm64-v8a
        android.permissions = INTERNET,ACCESS_NETWORK_STATE
        EOF
        
        buildozer android debug --verbose

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: mix-cd-scrobbler-apk
        path: bin/*.apk
